### ISSUE TITLE
Trouble getting plugin to work on ubuntu 16.04 + php 7

### ISSUE THREAD

**Issue by NicolasDaigneault** [joshp23/YOURLS-IQRCodes#3]
I'm not able to make the plugin work with ubuntu server 16 and php 7.  If I activate the plugin the result page of a shorten url is blank.  I have this error message in apache log:

 PHP Fatal error:  Uncaught Error: Access to undeclared static property: QRcode::$opt in /var/www/monurl/YOURLS/user/plugins/iqrcodes/plugin.php:389\nStack trace:\n#0 /var/www/monurl/YOURLS/includes/functions-plugins.php(150): iqrcodes_add_url(Array, 'http://www.cssh...', 'testnickcssh2', '')\n#1 /var/www/monurl/YOURLS/includes/functions.php(301): yourls_apply_filter('add_new_link', Array, 'http://www.cssh...', 'testnickcssh2', '')\n#2 /var/www/monurl/YOURLS/sample-public-front-page.php(29): yourls_add_new_link('http://www.cssh...', 'testnickcssh2', '')\n#3 {main}\n  thrown in /var/www/monurl/YOURLS/user/plugins/iqrcodes/plugin.php on line 389, referer: http://monurl.ca/sample-public-front-page.php

**Comment by joshp23** [comment]
I haven't tested this with php7. Check permissions on `/var/www/monurl/YOURLS/user/plugins/iqrcodes/assets`

**Comment by joshp23** [comment]
Line 15 of plugin.php, `require_once( dirname(__FILE__).'/assets/phpqrcode.php' );`, handles importing the script that should take care of your issue. Without that file then the plugin wil ldo nothing but throw errors like the one you are experiencing.

**Comment by wackerm** [comment]
I had the same issue using PHP7 (php7.0-fpm + nginx + Debian Jessie).
I  checked the permissions to include the library, but they were all fine.
I also checked, if the phpqrcode library from https://sourceforge.net/projects/phpqrcode/ works with PHP 7.0 and it works.

The issue is caused by the change how php 7 handles indirect expressions (https://secure.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect)

**Solution:**
Change from
`QRcode::$opt[5]`
To:
`QRcode::{$opt[5]}`

**Comment by joshp23** [comment]
will that change break previous versions of PHP? If so, I'll create another branch, if not I'll work on updating it as time permits. Probably in about 2 weeks.

**Comment by wackerm** [comment]
No, this should not break previous versions of PHP, since only the defaults are changed.
